# $FreeBSD$

SUBDIR=	\
	iwlwifi-3160-fw \
	iwlwifi-3168-fw \
	iwlwifi-7260-fw \
	iwlwifi-7265-fw \
	iwlwifi-7265D-fw \
	iwlwifi-8000C-fw \
	iwlwifi-8265-fw \
	iwlwifi-9000-pu-b0-jf-b0-fw \
	iwlwifi-9260-th-b0-jf-b0-fw \
	iwlwifi-Qu-b0-hr-b0-fw \
	iwlwifi-Qu-b0-jf-b0-fw \
	iwlwifi-Qu-c0-hr-b0-fw \
	iwlwifi-Qu-c0-jf-b0-fw \
	iwlwifi-QuZ-a0-hr-b0-fw \
	iwlwifi-QuZ-a0-jf-b0-fw \
	iwlwifi-cc-a0-fw

.include <bsd.subdir.mk>
