/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2020 The FreeBSD Foundation
 *
 * This software was developed by Björn Zeeb under sponsorship from
 * the FreeBSD Foundation.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * $FreeBSD$
 */

#ifndef	_NET_IEEE80211_RADIOTAP_H
#define	_NET_IEEE80211_RADIOTAP_H

#define	IEEE80211_RADIOTAP_HE_DATA1_BEAM_CHANGE_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_BSS_COLOR_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_BW_RU_ALLOC_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_CODING_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_DATA_DCM_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_DATA_MCS_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_DOPPLER_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_FORMAT_EXT_SU	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_FORMAT_MU	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_FORMAT_SU	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_FORMAT_TRIG	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_LDPC_XSYMSEG_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_SPTL_REUSE2_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_SPTL_REUSE3_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_SPTL_REUSE4_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_SPTL_REUSE_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_STBC_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA1_UL_DL_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_GI_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_NUM_LTF_SYMS_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_PE_DISAMBIG_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_PRE_FEC_PAD_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_PRISEC_80_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_PRISEC_80_SEC	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_RU_OFFSET	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_RU_OFFSET_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_TXBF_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA2_TXOP_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA3_BEAM_CHANGE	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA3_BSS_COLOR	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA3_LDPC_XSYMSEG	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA3_UL_DL	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA4_SU_MU_SPTL_REUSE	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA4_TB_SPTL_REUSE1	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA4_TB_SPTL_REUSE2	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA4_TB_SPTL_REUSE3	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA4_TB_SPTL_REUSE4	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA5_NUM_LTF_SYMS	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA5_PE_DISAMBIG	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA5_PRE_FEC_PAD	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA5_TXBF	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA6_DOPPLER	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA6_TB_PPDU_BW	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA6_TB_PPDU_BW_160MHZ	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA6_TB_PPDU_BW_20MHZ	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA6_TB_PPDU_BW_40MHZ	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA6_TB_PPDU_BW_80MHZ	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA6_TB_PPDU_BW_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA6_TXOP		__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_CH1_CTR_26T_RU	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_CH1_CTR_26T_RU_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_CH1_RU_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_CH2_CTR_26T_RU_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_CH2_RU_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_SIG_B_COMP_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_SIG_B_DCM	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_SIG_B_DCM_KNOWN		__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_SIG_B_MCS	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_SIG_B_MCS_KNOWN		__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS1_SIG_B_SYMS_USERS_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_BW_FROM_SIG_A_BW	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_BW_FROM_SIG_A_BW_160MHZ	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_BW_FROM_SIG_A_BW_20MHZ	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_BW_FROM_SIG_A_BW_40MHZ	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_BW_FROM_SIG_A_BW_80MHZ	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_BW_FROM_SIG_A_BW_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_CH2_CTR_26T_RU		__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_PUNC_FROM_SIG_A_BW	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_PUNC_FROM_SIG_A_BW_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_SIG_B_COMP	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_MU_FLAGS2_SIG_B_SYMS_USERS	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_LSIG_DATA1_LENGTH_KNOWN	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_LSIG_DATA2_LENGTH	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_MCS_HAVE_FEC		__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_MCS_HAVE_STBC	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_TIMESTAMP_SPOS_PLCP_SIG_ACQ	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_TIMESTAMP_UNIT_US	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_VHT_KNOWN_BEAMFORMED			0x20	/* net80211: IEEE80211_RADIOTAP_VHT_BF */
#define	IEEE80211_RADIOTAP_VHT_KNOWN_STBC			0x01	/* net80211: IEEE80211_RADIOTAP_VHT_STBC */
#define	IEEE80211_RADIOTAP_ZERO_LEN_PSDU_NOT_CAPTURED	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_ZERO_LEN_PSDU_SOUNDING	__LINE__ /* TODO FIXME */
#define	IEEE80211_RADIOTAP_ZERO_LEN_PSDU_VENDOR	__LINE__ /* TODO FIXME */


#define	IEEE80211_RADIOTAP_HE_DATA5_LTF_SIZE	0x00c0
#define	IEEE80211_RADIOTAP_HE_DATA5_LTF_SIZE_1X	1 /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA5_LTF_SIZE_2X	2 /* TODO FIXME */
#define	IEEE80211_RADIOTAP_HE_DATA5_LTF_SIZE_4X	3 /* TODO FIXME */

struct ieee80211_radiotap_he {
	/* TODO FIXME */
	int		data1, data2, data3, data4, data5, data6;
};

struct ieee80211_radiotap_he_mu {
	/* TODO FIXME */
	int		flags1, flags2;
	uint8_t		ru_ch1[4];
	uint8_t		ru_ch2[4];
};

struct ieee80211_radiotap_lsig {
	/* TODO FIXME */
	int		data1, data2;
};

struct ieee80211_vendor_radiotap {
	/* TODO FIXME */
	int		align, len, pad, present, subns;
	u8		oui[3];
	u8		data[0];
};


#endif	/* _NET_IEEE80211_RADIOTAP_H */

/* end */
