/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2020 The FreeBSD Foundation
 *
 * This software was developed by Björn Zeeb under sponsorship from
 * the FreeBSD Foundation.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * $FreeBSD$
 */

#ifndef	_LINUX_NL80211_H
#define	_LINUX_NL80211_H

#define	NL80211_FEATURE_AP_MODE_CHAN_WIDTH_CHANGE	__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_DS_PARAM_SET_IE_IN_PROBES	__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_HT_IBSS				__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_LOW_PRIORITY_SCAN		__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_ND_RANDOM_MAC_ADDR		__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_P2P_GO_CTWIN			__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_P2P_GO_OPPPS			__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_QUIET				__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_SCAN_RANDOM_MAC_ADDR		__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_SCHED_SCAN_RANDOM_MAC_ADDR	__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_DYNAMIC_SMPS			__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_STATIC_SMPS			__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_SUPPORTS_WMM_ADMISSION		__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_TDLS_CHANNEL_SWITCH		__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_TX_POWER_INSERTION		__LINE__ /* TODO FIXME */
#define	NL80211_FEATURE_WFA_TPC_IE_IN_PROBES		__LINE__ /* TODO FIXME */
#define	NL80211_MAX_SUPP_REG_RULES			__LINE__ /* TODO FIXME */
#define	NL80211_PMSR_FTM_FAILURE_NO_RESPONSE		__LINE__ /* TODO FIXME */
#define	NL80211_PMSR_FTM_FAILURE_PEER_BUSY		__LINE__ /* TODO FIXME */
#define	NL80211_PMSR_FTM_FAILURE_UNSPECIFIED		__LINE__ /* TODO FIXME */
#define	NL80211_PMSR_STATUS_FAILURE			__LINE__ /* TODO FIXME */
#define	NL80211_PMSR_STATUS_SUCCESS			__LINE__ /* TODO FIXME */
#define	NL80211_PMSR_STATUS_TIMEOUT			__LINE__ /* TODO FIXME */
#define	NL80211_PMSR_TYPE_FTM				__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_GI_0_8			__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_GI_1_6			__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_GI_3_2			__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_RU_ALLOC_106		__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_RU_ALLOC_242		__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_RU_ALLOC_26		__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_RU_ALLOC_2x996		__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_RU_ALLOC_484		__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_RU_ALLOC_52		__LINE__ /* TODO FIXME */
#define	NL80211_RATE_INFO_HE_RU_ALLOC_996		__LINE__ /* TODO FIXME */
#define	NL80211_RRF_AUTO_BW				__LINE__ /* TODO FIXME */
#define	NL80211_RRF_DFS					__LINE__ /* TODO FIXME */
#define	NL80211_RRF_GO_CONCURRENT			__LINE__ /* TODO FIXME */
#define	NL80211_RRF_NO_160MHZ				__LINE__ /* TODO FIXME */
#define	NL80211_RRF_NO_80MHZ				__LINE__ /* TODO FIXME */
#define	NL80211_RRF_NO_HT40				__LINE__ /* TODO FIXME */
#define	NL80211_RRF_NO_HT40MINUS			__LINE__ /* TODO FIXME */
#define	NL80211_RRF_NO_HT40PLUS				__LINE__ /* TODO FIXME */
#define	NL80211_RRF_NO_IR				__LINE__ /* TODO FIXME */
#define	NL80211_RRF_NO_OUTDOOR				__LINE__ /* TODO FIXME */
#define	NL80211_RRF_NO_HE				__LINE__ /* TODO FIXME */
#define	NL80211_SCAN_FLAG_FILS_MAX_CHANNEL_TIME		__LINE__ /* TODO FIXME */
#define	NL80211_SCAN_FLAG_OCE_PROBE_REQ_DEFERRAL_SUPPRESSION	__LINE__ /* TODO FIXME */
#define	NL80211_SCAN_FLAG_OCE_PROBE_REQ_HIGH_TX_RATE	__LINE__ /* TODO FIXME */
#define	NL80211_SCAN_FLAG_RANDOM_ADDR			__LINE__ /* TODO FIXME */
#define	NL80211_REGDOM_SET_BY_USER			__LINE__ /* TODO FIXME */

enum nl80211_band {
	/* XXX TODO */
	NL80211_BAND_2GHZ	= 0,
	NL80211_BAND_5GHZ,

	/* Keep this last. */
	NUM_NL80211_BANDS
};

enum nl80211_chan_flags {
	/* XXX TODO */
	NL80211_CHAN_NO_HT,
};

enum nl80211_chan_width {
	/* XXX TODO */
	NL80211_CHAN_WIDTH_20,
	NL80211_CHAN_WIDTH_20_NOHT,
	NL80211_CHAN_WIDTH_40,
	NL80211_CHAN_WIDTH_80,
	NL80211_CHAN_WIDTH_160,
};

enum nl80211_iftype {
	/* XXX TODO */
	NL80211_IFTYPE_UNSPECIFIED,
	NL80211_IFTYPE_ADHOC,
	NL80211_IFTYPE_STATION,
	NL80211_IFTYPE_AP,
	NL80211_IFTYPE_MONITOR,
	NL80211_IFTYPE_P2P_CLIENT,
	NL80211_IFTYPE_P2P_DEVICE,
	NL80211_IFTYPE_P2P_GO,
	NL80211_IFTYPE_MESH_POINT,
};

enum nl80211_preamble {
	/* XXX TODO */
	NL80211_PREAMBLE_LEGACY,
	NL80211_PREAMBLE_HT,
	NL80211_PREAMBLE_VHT,
	NL80211_PREAMBLE_HE,
};

enum nl80211_tdls_operation {
	/* XXX TODO */
	NL80211_TDLS_SETUP,
	NL80211_TDLS_TEARDOWN,
	NL80211_TDLS_ENABLE_LINK,
	NL80211_TDLS_DISABLE_LINK,
	NL80211_TKIP_DATA_OFFSET_RX_MIC_KEY,
	NL80211_TKIP_DATA_OFFSET_TX_MIC_KEY,
};

enum nl80211_cqm_rssi_threshold_event {
	/* XXX TODO */
	NL80211_CQM_RSSI_THRESHOLD_EVENT_LOW,
	NL80211_CQM_RSSI_THRESHOLD_EVENT_HIGH,
};

enum nl80211_ext_feature {
	/* XXX TODO */
	NL80211_EXT_FEATURE_ACCEPT_BCAST_PROBE_RESP,
	NL80211_EXT_FEATURE_BSS_PARENT_TSF,
	NL80211_EXT_FEATURE_ENABLE_FTM_RESPONDER,
	NL80211_EXT_FEATURE_FILS_MAX_CHANNEL_TIME,
	NL80211_EXT_FEATURE_MU_MIMO_AIR_SNIFFER,
	NL80211_EXT_FEATURE_OCE_PROBE_REQ_DEFERRAL_SUPPRESSION,
	NL80211_EXT_FEATURE_OCE_PROBE_REQ_HIGH_TX_RATE,
	NL80211_EXT_FEATURE_SCAN_START_TIME,
	NL80211_EXT_FEATURE_SET_SCAN_DWELL,
	NL80211_EXT_FEATURE_VHT_IBSS,
	NL80211_EXT_FEATURE_CAN_REPLACE_PTK0,
};

enum nl80211_sta_info {
	/* XXX TODO */
	NL80211_STA_INFO_BEACON_RX,
	NL80211_STA_INFO_BEACON_SIGNAL_AVG,
	NL80211_STA_INFO_SIGNAL_AVG,
	NL80211_STA_INFO_TX_BITRATE,
};

enum nl80211_ftm_stats {
	/* XXX TODO */
	NL80211_FTM_STATS_ASAP_NUM,
	NL80211_FTM_STATS_FAILED_NUM,
	NL80211_FTM_STATS_NON_ASAP_NUM,
	NL80211_FTM_STATS_OUT_OF_WINDOW_TRIGGERS_NUM,
	NL80211_FTM_STATS_PARTIAL_NUM,
	NL80211_FTM_STATS_RESCHEDULE_REQUESTS_NUM,
	NL80211_FTM_STATS_SUCCESS_NUM,
	NL80211_FTM_STATS_TOTAL_DURATION_MSEC,
	NL80211_FTM_STATS_UNKNOWN_TRIGGERS_NUM,
};

enum nl80211_reg_initiator {
	/* XXX TODO */
	_XXX_FXIME_RTW88_USES_ENUM,
};

#endif	/* _LINUX_NL80211_H */

/* end */
